В этом задании вы сможете немного расслабиться после реализации случайного леса и градиентного бустинга по мотивам материалов прошлой недели. Все, что нужно будет делать — запускать методы из sklearn. Вам предлагается выяснить, какое распределение лучше использовать в наивном байесовском классификаторе в зависимости от вида признаков.

Загрузите датасеты digits и breast_cancer из sklearn.datasets. Выведите несколько строчек из обучающих выборок и посмотрите на признаки. С помощью sklearn.cross_validation.cross_val_score c настройками по умолчанию и вызова метода mean() у возвращаемого этой функцией numpy.ndarray, сравните качество работы наивных байесовских классификаторов на этих двух датасетах. Для сравнения предлагается использовать BernoulliNB, MultinomialNB и GaussianNB. Насколько полученные результаты согласуются с рекомендациями из лекций?

Два датасета, конечно, еще не повод делать далеко идущие выводы, но при желании вы можете продолжить исследование на других выборках (например, из UCI репозитория).

Для сдачи задания, ответьте на приведенные ниже вопросы.

In [1]:
from sklearn import metrics, datasets, model_selection
from sklearn.naive_bayes import BernoulliNB, MultinomialNB, GaussianNB


In [2]:
X1, y1 = datasets.load_breast_cancer(return_X_y = True)

In [3]:
X2, y2 = datasets.load_digits(return_X_y = True)

In [4]:
print (X1)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [5]:
print (X2)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


Вопрос 1

Каким получилось максимальное качество классификации на датасете breast_cancer?

In [6]:
model_selection.cross_val_score(BernoulliNB(), X1, y1).mean()

0.6274181027790716

In [7]:
model_selection.cross_val_score(MultinomialNB(), X1, y1).mean()

0.8963204471355379

In [8]:
model_selection.cross_val_score(GaussianNB(), X1, y1).mean()

0.9385188635305075

Вопрос 2

Каким получилось максимальное качество классификации на датасете digits?

In [9]:
model_selection.cross_val_score(BernoulliNB(), X2, y2).mean()

0.8241736304549674

In [10]:
model_selection.cross_val_score(MultinomialNB(), X2, y2).mean()

0.8703497369235531

In [11]:
model_selection.cross_val_score(GaussianNB(), X2, y2).mean()

0.8069281956050759

Вопрос 3

Выберите верные утверждения и запишите их номера через пробел (в порядке возрастания номера):

1) На вещественных признаках лучше всего сработал наивный байесовский классификатор с распределением Бернулли

2) На вещественных признаках лучше всего сработал наивный байесовский классификатор с мультиномиальным распределением

3) Мультиномиальное распределение лучше показало себя на выборке с целыми неотрицательными значениями признаков

4) На вещественных признаках лучше всего сработало нормальное распределение