Давайте уточним правило трёх сигм. Утверждение: 99.7% вероятностной массы случайной величины X\sim N\left(\mu,\sigma^2\right)X∼N(μ,σ 
2
 ) лежит в интервале \mu\pm c \cdot \sigmaμ±c⋅σ. Чему равно точное значение константы cc? Округлите ответ до четырёх знаков после десятичной точки.

In [3]:
import numpy as np
from scipy.stats import norm

In [6]:
norm.ppf(1 - 0.003/2.0)

2.9677379253417944

В пятилетнем рандомизированном исследовании Гарвардской медицинской школы 11037 испытуемых через день принимали аспирин, а ещё 11034 — плацебо. Исследование было слепым, то есть, испытуемые не знали, что именно они принимают.

За 5 лет инфаркт случился у 104 испытуемых, принимавших аспирин, и у 189 принимавших плацебо.

Оцените, насколько вероятность инфаркта снижается при приёме аспирина. Округлите ответ до четырёх знаков после десятичной точки.

In [12]:
p1 = 189/11034.0
p2 = 104/11037.0
p1 - p2

0.0077060239760047815

Постройте теперь 95% доверительный интервал для снижения вероятности инфаркта при приёме аспирина. Чему равна его верхняя граница? Округлите ответ до четырёх знаков после десятичной точки.



In [16]:
v = norm.ppf(1 - 0.05/2.0)
up = (p1 - p2) + v * np.sqrt(p1 * (1 - p1)/11034.0 + p2*(1 - p2)/11037.0)
print (up)

0.010724297276960124


In [17]:
def odds(p, n):
    return p/(n - p)

In [23]:
x1 = odds(189.0, 11034.0)
x2 = odds(104.0, 11037.0)
print(x1, x2)

0.017427385892116183 0.009512485136741973


In [24]:
print(x1/x2)

1.8320539419087138


По данным опроса, 75% работников ресторанов утверждают, что испытывают на работе существенный стресс, оказывающий негативное влияние на их личную жизнь. Крупная ресторанная сеть опрашивает 100 своих работников, чтобы выяснить, отличается ли уровень стресса работников в их ресторанах от среднего. 67 из 100 работников отметили высокий уровень стресса.

In [27]:
from scipy.stats import binom_test
binom_test(67, 100, 0.75)

0.08222258891386608

The Wage Tract — заповедник в округе Тома, Джорджия, США, деревья в котором не затронуты деятельностью человека со времён первых поселенцев. Для участка заповедника размером 200х200 м имеется информация о координатах сосен (sn — координата в направлении север-юг, we — в направлении запад-восток, обе от 0 до 200).

Проверим, можно ли пространственное распределение сосен считать равномерным, или они растут кластерами.

Загрузите данные, поделите участок на 5х5 одинаковых квадратов размера 40x40 м, посчитайте количество сосен в каждом квадрате (чтобы получить такой же результат, как у нас, используйте функцию scipy.stats.binned_statistic_2d).

Если сосны действительно растут равномерно, какое среднее ожидаемое количество сосен в каждом квадрате? В правильном ответе два знака после десятичной точки.

In [29]:
import pandas as pd
data = pd.read_csv("pines.txt", header = 0, sep = '\t')

In [32]:
data.head()

sn    we
0  200.0   8.8
1  199.3  10.0
2  193.6  22.4
3  167.7  35.6
4  183.9  45.4

In [36]:
data.describe()

sn          we
count  584.000000  584.000000
mean    98.735274  113.829281
std     56.523154   49.810725
min      0.000000    0.000000
25%     52.050000   79.125000
50%    101.450000  121.900000
75%    149.400000  149.725000
max    200.000000  200.000000

In [38]:
from scipy.stats import binned_statistic_2d

In [140]:
x = data.sn.values
y = data.we.values
bin = np.arange(0.0, 200.1, 40.)
values = []

In [141]:
ret = binned_statistic_2d(x, y, values, statistic='count', bins=[bin, bin])

In [142]:
print (ret.statistic)

[[18. 26. 29. 25. 20.]
 [14. 12. 22. 34. 25.]
 [12. 24. 15. 50. 37.]
 [ 8. 19. 31. 50.  7.]
 [ 7.  8. 37. 27. 27.]]


In [143]:
len(x) / 25

23.36

In [165]:
arr = [j  for i in ret.statistic for j in i]

In [166]:
from scipy.stats import chisquare
chi = chisquare(arr, ddof = 0)

In [167]:
print (chi)

Power_divergenceResult(statistic=150.58904109589042, pvalue=2.574669774967279e-20)
